- hosts: all
  become: no
  roles:
    - common
    - docker-install
  vars_prompt:
    - name: git_user
      private: no
    - name: git_pass
      private: yes


- hosts: devserver
  become: yes
  roles:
    - docker-swarm-init

  tasks:

- name: add workers to the swarm
  become: yes
  hosts: workers
  ignore_errors: yes
  roles:
    - docker-swarm-add-worker

- hosts: devserver
  gather_facts: no
  tasks:
     # Dask
    - name: Download git repository
      become: true
      git:
        repo: 'https://github.com/dask/dask-docker'
        dest: /dask-docker

    # Dev
    - name: Deploy stack from compose file
      become: yes
      community.docker.docker_stack:
        state: present
        name: mystack
        compose:
          - /github_stargazers_prediction/ci_cd/production_server/docker-compose.yml
          - /dask-docker/docker-compose.yml

    - name: Install python packages for dev host
      pip:
        requirements: /github_stargazers_prediction/requirements.txt

    - name: Install python packages for dev host
      pip:
        requirements: /github_stargazers_prediction/requirements.txt

    - name: Extract repos ever day
      ansible.builtin.cron:
        name: "extract repo"
        minute: "0"
        hour: "0"
        day: "*"
        job: "cd /github_stargazers_prediction/; python3 extract_repositories.py"
