- name: Extra packages
  apt: pkg={{item}} state=latest update_cache=true
  with_items:
   - apt-transport-https
   - ca-certificates
   - curl
   - software-properties-common
  become: true

- name: apt update
  apt: update_cache=yes upgrade=dist
  become: true

- name: Add Docker repository key
  apt_key:
   url: https://download.docker.com/linux/ubuntu/gpg
   state: present
  become: true

- name: Add Docker repository
  command: add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  become: true

- name: apt update
  apt: update_cache=yes upgrade=dist
  become: true

- name: Install Docker
  apt: pkg=docker-ce state=present update_cache=true allow_unauthenticated=yes
  become: true

