version: "3.1"
services:
  web:
    image: yasserkaddoura/proj_web:latest
    restart: always
    ports:
      - "5100:5100"
    depends_on:
      - rabbit
    volumes:
      - .:/app
  rabbit:
    hostname: rabbit
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  worker_1:
    image: yasserkaddoura/proj_web:latest
    hostname: worker_1
    entrypoint: celery
    command: -A workerA worker --loglevel=debug
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit
